### ISSUE TITLE
abnormal UTF characters generated in the sql file

### ISSUE THREAD

**Issue by hugoalopez-diku** [borkdominik/bigER#11]
The following is a very simple erd file:

entity Specializations{
    SpecializationId: int key
    name: string
}

which later becomes compiled in the following sql script:

CREATE TABLE Specializations (
	name varchar(255) NOT NULL, 		
	SpecializationId int NOT NULL		
	
	PRIMARY KEY (SpecializationId)
);

What is not seen is that each line is appended with a couple of tabulators, which render the file unusable for mysql:
![image](https://user-images.githubusercontent.com/79974488/161452009-0d3d3609-c405-4b16-ade4-00d7d5762364.png)

![image](https://user-images.githubusercontent.com/79974488/161452021-6ed3cccc-3632-4347-90e2-f791d6cf0814.png)

**Comment by plglaser** [comment]
Fixes for this are already available in the newest release on the marketplace. The last commit includes basic tests for the code generator that also ensure the correct handling of white spaces.
