### ISSUE TITLE
type with multi args

### ISSUE THREAD

**Issue by redaready** [borkdominik/bigER#28]
### Description

for  type  with 2 or more args, can not generate diagram 
example: amout: decimal(40, 20) 
error message:
mismatched input '40,20' expecting RULE_INT(org.eclipse.xtext.diagnostics.Diagnostic.Syntax)

**Comment by plglaser** [comment]
Datatypes with two arguments are now supported in the [latest release (v0.4.0) of bigER](https://marketplace.visualstudio.com/items?itemName=BIGModelingTools.erdiagram). 

Example Model:
```
erdiagram Model

entity Order {
    id: INTEGER key
    price: DOUBLE(5, 5) // datatype with two arguments
}
```
