### ISSUE TITLE
Feature Request: More types please

### ISSUE THREAD

**Issue by tommccallum** [borkdominik/bigER#4]
Type system is currently limiting, would like to have types catered for by MySQL, DB2 and Snowflake.

The biggest one I miss is being able to specify the string length e.g. varchar(20) rather than it always choosing varchar(255). 

Thanks

**Comment by plglaser** [comment]
The [new release of bigER](https://marketplace.visualstudio.com/items?itemName=BIGModelingTools.erdiagram) now allows specifying arbitrary data types for attributes, and is also supported in the SQL code generator.
